[project]
name = "goldencheetah-headless"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.0",
]

[dependency-groups]
dev = [
    "black>=24.10.0",
    "pyright>=1.1.392.post0",
]
